[package]
name = "ckb-test-chain-utils"
version = "0.34.1"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"
license = "MIT"

[dependencies]
ckb-types = {path = "../types"}
ckb-db = { path = "../../db" }
ckb-store = { path = "../../store" }
ckb-chain-spec = { path = "../../spec" }
ckb-dao-utils = { path = "../dao/utils" }
ckb-traits = { path = "../../traits" }
ckb-error = { path = "../../error" }
lazy_static = "1.3.0"
faketime = "0.2.0"
ckb-resource = { path = "../../resource" }
