[package]
name = "ckb-hash"
version = "0.43.0"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"
description = "CKB default hash function."
homepage = "https://github.com/nervosnetwork/ckb"
repository = "https://github.com/nervosnetwork/ckb"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
blake2b-rs = "0.1.5"

[target.'cfg(target_arch = "wasm32")'.dependencies]
blake2b-ref = "0.2.0"
