[advisories]
vulnerability = "deny"
unmaintained = "warn"
yanked = "deny"
notice = "deny"
ignore = [
    "RUSTSEC-2020-0043", # TODO ws allows remote attacker to run the process out of memory, since it is no longer actively maintained, we couldn't fix it in the short term
    "RUSTSEC-2020-0082", # TODO ordered_float:NotNan may contain NaN after panic in assignment operators
                         #      Could be removed after heim 0.1.0 released.
    "RUSTSEC-2021-0013", # TODO We did not use heim-virt to get cpu information
    "RUSTSEC-2021-0020", # TODO JsonRPC unable to upgrade, considering that the trigger condition is too harsh(upstream proxy and proxy is wrong), ignore it for now
]

[licenses]
unlicensed = "deny"
allow = [
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "CC0-1.0",
    "ISC",
    "MIT",
]
copyleft = "deny"
default = "deny"
exceptions = [
    { allow = ["BSD-3-Clause", "Zlib"], name = "adler32", version = "*" },
    { allow = ["MPL-2.0"], name = "attohttpc", version = "*" },
    { allow = ["MIT", "ISC", "OpenSSL"], name = "ring", version = "*" },
]

[[licenses.clarify]]
name = "ring"
version = "*"
expression = "MIT AND ISC AND OpenSSL"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 }
]

[bans]
multiple-versions = "warn"
wildcards = "deny"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
