[package]
name = "ckb-verification"
version = "0.43.0"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"
description = "The CKB verification"
homepage = "https://github.com/nervosnetwork/ckb"
repository = "https://github.com/nervosnetwork/ckb"

[dependencies]
ckb-types = { path = "../util/types", version = "= 0.43.0" }
ckb-script = { path = "../script", version = "= 0.43.0" }
ckb-pow = { path = "../pow", version = "= 0.43.0" }
faketime = "0.2.0"
lru = "0.6.0"
ckb-traits = { path = "../traits", version = "= 0.43.0" }
ckb-chain-spec = { path = "../spec", version = "= 0.43.0" }
ckb-dao = { path = "../util/dao", version = "= 0.43.0" }
ckb-dao-utils = { path = "../util/dao/utils", version = "= 0.43.0" }
ckb-error = { path = "../error", version = "= 0.43.0" }
derive_more = { version = "0.99.0", default-features=false, features = ["display"] }
ckb-verification-traits = { path = "./traits", version = "= 0.43.0" }
ckb-metrics = { path = "../util/metrics", version = "= 0.43.0" }

[dev-dependencies]
ckb-test-chain-utils = { path = "../util/test-chain-utils", version = "= 0.43.0" }
ckb-resource = { path = "../resource", version = "= 0.43.0" }
