[package]
name = "ckb-fee-estimator"
version = "0.43.0"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"
license = "MIT"
description = "CKB builtin fee estimator."
homepage = "https://github.com/nervosnetwork/ckb"
repository = "https://github.com/nervosnetwork/ckb"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ckb-types = { path = "../types", version = "= 0.43.0" }
ckb-logger = { path = "../logger", version = "= 0.43.0" }
serde = { version = "1.0", features = ["derive"] }
