[package]
name = "ckb-occupied-capacity"
version = "0.34.1"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"

[dependencies]
ckb-occupied-capacity-macros = { path = "macros" }
ckb-occupied-capacity-core = { path = "core" }
proc-macro-hack = "0.5"
