[package]
name = "ckb-reward-calculator"
version = "0.43.0"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"
description = "TODO(doc): @keroro520 crate description"
homepage = "https://github.com/nervosnetwork/ckb"
repository = "https://github.com/nervosnetwork/ckb"

[dependencies]
ckb-types = { path = "../types", version = "= 0.43.0" }
ckb-store = { path = "../../store", version = "= 0.43.0" }
ckb-dao = { path = "../dao", version = "= 0.43.0" }
ckb-logger = { path = "../logger", version = "= 0.43.0" }
ckb-chain-spec = {path = "../../spec", version = "= 0.43.0"}
ckb-error = { path = "../../error", version = "= 0.43.0" }

[dev-dependencies]
ckb-db = { path = "../../db", version = "= 0.43.0" }
ckb-occupied-capacity = { path = "../occupied-capacity", version = "= 0.43.0" }
ckb-db-schema = { path = "../../db-schema", version = "= 0.43.0" }
