[package]
name = "ckb-proposal-table"
version = "0.34.1"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"
license = "MIT"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ckb-logger = { path = "../logger" }
ckb-chain-spec = { path = "../../spec" }
ckb-types = { path = "../types" }
