[package]
name = "ckb-network"
version = "0.30.1-pre"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"

[dependencies]
rand = "0.6"
serde = { version = "1.0", features = ["derive"] }
ckb-util = { path = "../util" }
ckb-stop-handler = { path = "../util/stop-handler" }
ckb-logger = { path = "../util/logger" }
tokio = "0.1.18"
tokio-threadpool = "0.1"
futures = "0.1"
crossbeam-channel = "0.3"
p2p = { version="0.2.7", package="tentacle", features = ["molc"] }
p2p-ping = { package="ckb-ping", path = "../protocols/ping" }
p2p-discovery = { package="ckb-discovery", path = "../protocols/discovery" }
p2p-identify = { package="ckb-identify", path = "../protocols/identify" }
faketime = "0.2.0"
lazy_static = "1.3.0"
bs58 = "0.3.0"
sentry = "0.16.0"
faster-hex = "0.4"
ckb-hash = {path = "../util/hash"}
secp256k1 = {version = "0.15.0", features = ["recovery"] }
resolve = "0.2.0"
ckb-build-info = {path = "../util/build-info"}
num_cpus = "1.10"
snap = "0.2"
ckb-types = { path = "../util/types" }
ipnetwork = "0.14"
serde_json = "1.0"
tempfile = "3.0.7"

[dev-dependencies]
criterion = "0.3"
proptest = "0.9"

[[bench]]
name = "peer_store"
harness = false
path = "src/benches/peer_store.rs"
