[package]
name = "ckb-wasm-test"
version = "0.30.1-pre"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"

[dependencies]
ckb-types = { path = "../util/types" }

[dependencies.ckb-script]
path = "../script"
default-features = false
features = []

# Prevent this from interfering with workspaces
[workspace]
members = ["."]
