[package]
name = "ckb-resource"
version = "0.43.0"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"
build = "build.rs"
description = "Bundled resources for the CKB binary."
homepage = "https://github.com/nervosnetwork/ckb"
repository = "https://github.com/nervosnetwork/ckb"

[dependencies]
phf = "0.7.21"
includedir = "0.5.0"
# Lock tempfile so wasm-build-test will use getrandom 0.1.*
tempfile = "=3.1.0"
serde = { version = "1.0", features = ["derive"] }
ckb-types = { path = "../util/types", version = "= 0.43.0" }
ckb-system-scripts = { version = "= 0.5.2" }

[build-dependencies]
includedir_codegen = "0.5.0"
walkdir = "2.1.4"
ckb-types = { path = "../util/types", version = "= 0.43.0" }
ckb-system-scripts = { version = "= 0.5.2" }
