[package]
name = "ckb-db"
version = "0.43.0"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"
description = "The ckb data persistent implementation"
homepage = "https://github.com/nervosnetwork/ckb"
repository = "https://github.com/nervosnetwork/ckb"

[dependencies]
ckb-app-config = { path = "../util/app-config", version = "= 0.43.0" }
ckb-logger = { path = "../util/logger", version = "= 0.43.0" }
ckb-error = { path = "../error", version = "= 0.43.0" }
libc = "0.2"
rocksdb = { package = "ckb-rocksdb", version ="=0.16.0", features = ["snappy"] }
ckb-db-schema = { path = "../db-schema", version = "= 0.43.0" }
tempfile = "3.0"
